//BUSCANDO TODOS OS PRESTADORES
GET http://localhost:6010/api/prestador HTTP/1.1
Content-Type: application/json


###
//BUSCANDO O PRESTADOR COM O CPF
GET  http://localhost:6010/api/prestador/12223338811 HTTP/1.1
Content-Type: application/json


###
//CRIANDO O PRESTADOR
POST http://localhost:6010/api/prestador/ HTTP/1.1
Content-Type: application/json

{
    "codigo_prestador": 3,
    "nome_prestador":"João ricardo",
    "cpf_prestador":"00011122235"
}


###
//ATUALIZANDO O USUARIO
PUT http://localhost:6010/api/prestador/3 HTTP/1.1
Content-Type: application/json

{
    "nome_prestador":"Miguel ricardo",
    "cpf_prestado":"11155889785"
}


###
//DELETANDO O USUARIO
DELETE http://localhost:6010/api/prestador/0 HTTP/1.1
Content-Type: application/json

###